/*Generated by WaveMaker Studio*/

package com.mobile_widgets_variables.classicmodels.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.mobile_widgets_variables.classicmodels.service.ClassicmodelsQueryExecutorService;
import com.mobile_widgets_variables.classicmodels.models.query.*;

@RestController(value = "Classicmodels.QueryExecutionController")
@RequestMapping("/classicmodels/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private ClassicmodelsQueryExecutorService queryService;

    @RequestMapping(value = "/queries/Emp", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "data")
    public Page<EmpResponse> executeEmp(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: Emp");
        Page<EmpResponse> _result = queryService.executeEmp(pageable);
        LOGGER.debug("got the result for named query: Emp, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query Emp")
    @RequestMapping(value = "/queries/Emp/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportEmp(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: Emp");

        return queryService.exportEmp(exportType, pageable);
    }

}


