/*Generated by WaveMaker Studio*/
package com.mobile_widgets_variables.classicmodels.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EmpResponse implements Serializable {


    @ColumnAlias("employeeNumber")
    private Integer employeeNumber;

    @ColumnAlias("lastName")
    private String lastName;

    @ColumnAlias("firstName")
    private String firstName;

    @ColumnAlias("extension")
    private String extension;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("officeCode")
    private String officeCode;

    @ColumnAlias("reportsTo")
    private Integer reportsTo;

    @ColumnAlias("jobTitle")
    private String jobTitle;

    public Integer getEmployeeNumber() {
        return this.employeeNumber;
    }

    public void setEmployeeNumber(Integer employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOfficeCode() {
        return this.officeCode;
    }

    public void setOfficeCode(String officeCode) {
        this.officeCode = officeCode;
    }

    public Integer getReportsTo() {
        return this.reportsTo;
    }

    public void setReportsTo(Integer reportsTo) {
        this.reportsTo = reportsTo;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmpResponse)) return false;
        final EmpResponse empResponse = (EmpResponse) o;
        return Objects.equals(getEmployeeNumber(), empResponse.getEmployeeNumber()) &&
                Objects.equals(getLastName(), empResponse.getLastName()) &&
                Objects.equals(getFirstName(), empResponse.getFirstName()) &&
                Objects.equals(getExtension(), empResponse.getExtension()) &&
                Objects.equals(getEmail(), empResponse.getEmail()) &&
                Objects.equals(getOfficeCode(), empResponse.getOfficeCode()) &&
                Objects.equals(getReportsTo(), empResponse.getReportsTo()) &&
                Objects.equals(getJobTitle(), empResponse.getJobTitle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeNumber(),
                getLastName(),
                getFirstName(),
                getExtension(),
                getEmail(),
                getOfficeCode(),
                getReportsTo(),
                getJobTitle());
    }
}
