/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.mobile_widgets_variables.classicmodels;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`orderdetails`")
@IdClass(OrderdetailsId.class)
public class Orderdetails implements Serializable {

    private Integer orderNumber;
    private String productCode;
    private int quantityOrdered;
    private BigDecimal priceEach;
    private short orderLineNumber;
    private Products productsByProductCode;
    private Orders ordersByOrderNumber;
    private Products productsByProductCodeRelation;
    private Orders ordersByOrderNumberRelation;

    @Id
    @Column(name = "`orderNumber`", nullable = false, scale = 0, precision = 10)
    public Integer getOrderNumber() {
        return this.orderNumber;
    }

    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    @Id
    @Column(name = "`productCode`", nullable = false, length = 15)
    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    @Column(name = "`quantityOrdered`", nullable = false, scale = 0, precision = 10)
    public int getQuantityOrdered() {
        return this.quantityOrdered;
    }

    public void setQuantityOrdered(int quantityOrdered) {
        this.quantityOrdered = quantityOrdered;
    }

    @Column(name = "`priceEach`", nullable = false, scale = 9, precision = 22)
    public BigDecimal getPriceEach() {
        return this.priceEach;
    }

    public void setPriceEach(BigDecimal priceEach) {
        this.priceEach = priceEach;
    }

    @Column(name = "`orderLineNumber`", nullable = false, scale = 0, precision = 5)
    public short getOrderLineNumber() {
        return this.orderLineNumber;
    }

    public void setOrderLineNumber(short orderLineNumber) {
        this.orderLineNumber = orderLineNumber;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`productCode`", referencedColumnName = "`productCode`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`orderdetails_ibfk_2`"))
    public Products getProductsByProductCode() {
        return this.productsByProductCode;
    }

    public void setProductsByProductCode(Products productsByProductCode) {
        if(productsByProductCode != null) {
            this.productCode = productsByProductCode.getProductCode();
        }

        this.productsByProductCode = productsByProductCode;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`orderNumber`", referencedColumnName = "`orderNumber`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FKpesxkfgjhtmmxwomn48f6ucmo`"))
    public Orders getOrdersByOrderNumber() {
        return this.ordersByOrderNumber;
    }

    public void setOrdersByOrderNumber(Orders ordersByOrderNumber) {
        if(ordersByOrderNumber != null) {
            this.orderNumber = ordersByOrderNumber.getOrderNumber();
        }

        this.ordersByOrderNumber = ordersByOrderNumber;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`productCode`", referencedColumnName = "`productCode`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK2d142hnoftqv0mkjlfc0r4hc9`"))
    public Products getProductsByProductCodeRelation() {
        return this.productsByProductCodeRelation;
    }

    public void setProductsByProductCodeRelation(Products productsByProductCodeRelation) {
        if(productsByProductCodeRelation != null) {
            this.productCode = productsByProductCodeRelation.getProductCode();
        }

        this.productsByProductCodeRelation = productsByProductCodeRelation;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`orderNumber`", referencedColumnName = "`orderNumber`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`orderdetails_ibfk_1`"))
    public Orders getOrdersByOrderNumberRelation() {
        return this.ordersByOrderNumberRelation;
    }

    public void setOrdersByOrderNumberRelation(Orders ordersByOrderNumberRelation) {
        if(ordersByOrderNumberRelation != null) {
            this.orderNumber = ordersByOrderNumberRelation.getOrderNumber();
        }

        this.ordersByOrderNumberRelation = ordersByOrderNumberRelation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Orderdetails)) return false;
        final Orderdetails orderdetails = (Orderdetails) o;
        return Objects.equals(getOrderNumber(), orderdetails.getOrderNumber()) &&
                Objects.equals(getProductCode(), orderdetails.getProductCode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderNumber(),
                getProductCode());
    }
}

