/*Generated by WaveMaker Studio*/

package com.mobile_widgets_variables.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.mobile_widgets_variables.classicmodels.models.procedure.*;

public interface ClassicmodelsProcedureExecutorService {

    ProResponse executePro(Integer _count, Integer inc);

}


