/*Generated by WaveMaker Studio*/

package com.mobile_widgets_variables.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobile_widgets_variables.classicmodels.models.query.*;

@Service
public class ClassicmodelsQueryExecutorServiceImpl implements ClassicmodelsQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClassicmodelsQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("classicmodelsWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<EmpResponse> executeEmp(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("Emp", params, EmpResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Downloadable exportEmp(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("Emp", params, exportType, EmpResponse.class, pageable);
    }

}


