/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.mobile_widgets_variables.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobile_widgets_variables.classicmodels.Customers;
import com.mobile_widgets_variables.classicmodels.Employees;


/**
 * ServiceImpl object for domain model class Employees.
 *
 * @see Employees
 */
@Service("classicmodels.EmployeesService")
@Validated
public class EmployeesServiceImpl implements EmployeesService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeesServiceImpl.class);

    @Lazy
    @Autowired
	@Qualifier("classicmodels.CustomersService")
	private CustomersService customersService;

    @Autowired
    @Qualifier("classicmodels.EmployeesDao")
    private WMGenericDao<Employees, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Employees, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "classicmodelsTransactionManager")
    @Override
	public Employees create(Employees employees) {
        LOGGER.debug("Creating a new Employees with information: {}", employees);
        Employees employeesCreated = this.wmGenericDao.create(employees);
        if(employeesCreated.getCustomersesForSalesRepEmployeeNumber() != null) {
            for(Customers customersesForSalesRepEmployeeNumber : employeesCreated.getCustomersesForSalesRepEmployeeNumber()) {
                customersesForSalesRepEmployeeNumber.setEmployeesBySalesRepEmployeeNumber(employeesCreated);
                LOGGER.debug("Creating a new child Customers with information: {}", customersesForSalesRepEmployeeNumber);
                customersService.create(customersesForSalesRepEmployeeNumber);
            }
        }

        if(employeesCreated.getCustomersesForSalesRepEmployeeNumberRelation() != null) {
            for(Customers customersesForSalesRepEmployeeNumberRelation : employeesCreated.getCustomersesForSalesRepEmployeeNumberRelation()) {
                customersesForSalesRepEmployeeNumberRelation.setEmployeesBySalesRepEmployeeNumberRelation(employeesCreated);
                LOGGER.debug("Creating a new child Customers with information: {}", customersesForSalesRepEmployeeNumberRelation);
                customersService.create(customersesForSalesRepEmployeeNumberRelation);
            }
        }

        if(employeesCreated.getEmployeesesForReportsTo() != null) {
            for(Employees employeesesForReportsTo : employeesCreated.getEmployeesesForReportsTo()) {
                employeesesForReportsTo.setEmployeesByReportsTo(employeesCreated);
                LOGGER.debug("Creating a new child Employees with information: {}", employeesesForReportsTo);
                create(employeesesForReportsTo);
            }
        }

        if(employeesCreated.getEmployeesesForReportsToRelation() != null) {
            for(Employees employeesesForReportsToRelation : employeesCreated.getEmployeesesForReportsToRelation()) {
                employeesesForReportsToRelation.setEmployeesByReportsToRelation(employeesCreated);
                LOGGER.debug("Creating a new child Employees with information: {}", employeesesForReportsToRelation);
                create(employeesesForReportsToRelation);
            }
        }
        return employeesCreated;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Employees getById(Integer employeesId) throws EntityNotFoundException {
        LOGGER.debug("Finding Employees by id: {}", employeesId);
        Employees employees = this.wmGenericDao.findById(employeesId);
        if (employees == null){
            LOGGER.debug("No Employees found with id: {}", employeesId);
            throw new EntityNotFoundException(String.valueOf(employeesId));
        }
        return employees;
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Employees findById(Integer employeesId) {
        LOGGER.debug("Finding Employees by id: {}", employeesId);
        return this.wmGenericDao.findById(employeesId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "classicmodelsTransactionManager")
	@Override
	public Employees update(Employees employees) throws EntityNotFoundException {
        LOGGER.debug("Updating Employees with information: {}", employees);
        this.wmGenericDao.update(employees);

        Integer employeesId = employees.getEmployeeNumber();

        return this.wmGenericDao.findById(employeesId);
    }

    @Transactional(value = "classicmodelsTransactionManager")
	@Override
	public Employees delete(Integer employeesId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Employees with id: {}", employeesId);
        Employees deleted = this.wmGenericDao.findById(employeesId);
        if (deleted == null) {
            LOGGER.debug("No Employees found with id: {}", employeesId);
            throw new EntityNotFoundException(String.valueOf(employeesId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Page<Employees> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Employees");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Employees> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Employees");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service classicmodels for table Employees to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Customers> findAssociatedCustomersesForSalesRepEmployeeNumber(Integer employeeNumber, Pageable pageable) {
        LOGGER.debug("Fetching all associated customersesForSalesRepEmployeeNumber");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeesBySalesRepEmployeeNumber.employeeNumber = '" + employeeNumber + "'");

        return customersService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Customers> findAssociatedCustomersesForSalesRepEmployeeNumberRelation(Integer employeeNumber, Pageable pageable) {
        LOGGER.debug("Fetching all associated customersesForSalesRepEmployeeNumberRelation");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeesBySalesRepEmployeeNumberRelation.employeeNumber = '" + employeeNumber + "'");

        return customersService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Employees> findAssociatedEmployeesesForReportsTo(Integer employeeNumber, Pageable pageable) {
        LOGGER.debug("Fetching all associated employeesesForReportsTo");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeesByReportsTo.employeeNumber = '" + employeeNumber + "'");

        return findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Employees> findAssociatedEmployeesesForReportsToRelation(Integer employeeNumber, Pageable pageable) {
        LOGGER.debug("Fetching all associated employeesesForReportsToRelation");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeesByReportsToRelation.employeeNumber = '" + employeeNumber + "'");

        return findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service CustomersService instance
	 */
	protected void setCustomersService(CustomersService service) {
        this.customersService = service;
    }

}

