/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.mobile_widgets_variables.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobile_widgets_variables.classicmodels.Orderdetails;
import com.mobile_widgets_variables.classicmodels.Products;


/**
 * ServiceImpl object for domain model class Products.
 *
 * @see Products
 */
@Service("classicmodels.ProductsService")
@Validated
public class ProductsServiceImpl implements ProductsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProductsServiceImpl.class);

    @Lazy
    @Autowired
	@Qualifier("classicmodels.OrderdetailsService")
	private OrderdetailsService orderdetailsService;

    @Autowired
    @Qualifier("classicmodels.ProductsDao")
    private WMGenericDao<Products, String> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Products, String> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "classicmodelsTransactionManager")
    @Override
	public Products create(Products products) {
        LOGGER.debug("Creating a new Products with information: {}", products);
        Products productsCreated = this.wmGenericDao.create(products);
        if(productsCreated.getOrderdetailsesForProductCode() != null) {
            for(Orderdetails orderdetailsesForProductCode : productsCreated.getOrderdetailsesForProductCode()) {
                orderdetailsesForProductCode.setProductsByProductCode(productsCreated);
                LOGGER.debug("Creating a new child Orderdetails with information: {}", orderdetailsesForProductCode);
                orderdetailsService.create(orderdetailsesForProductCode);
            }
        }

        if(productsCreated.getOrderdetailsesForProductCodeRelation() != null) {
            for(Orderdetails orderdetailsesForProductCodeRelation : productsCreated.getOrderdetailsesForProductCodeRelation()) {
                orderdetailsesForProductCodeRelation.setProductsByProductCodeRelation(productsCreated);
                LOGGER.debug("Creating a new child Orderdetails with information: {}", orderdetailsesForProductCodeRelation);
                orderdetailsService.create(orderdetailsesForProductCodeRelation);
            }
        }
        return productsCreated;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Products getById(String productsId) throws EntityNotFoundException {
        LOGGER.debug("Finding Products by id: {}", productsId);
        Products products = this.wmGenericDao.findById(productsId);
        if (products == null){
            LOGGER.debug("No Products found with id: {}", productsId);
            throw new EntityNotFoundException(String.valueOf(productsId));
        }
        return products;
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Products findById(String productsId) {
        LOGGER.debug("Finding Products by id: {}", productsId);
        return this.wmGenericDao.findById(productsId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "classicmodelsTransactionManager")
	@Override
	public Products update(Products products) throws EntityNotFoundException {
        LOGGER.debug("Updating Products with information: {}", products);
        this.wmGenericDao.update(products);

        String productsId = products.getProductCode();

        return this.wmGenericDao.findById(productsId);
    }

    @Transactional(value = "classicmodelsTransactionManager")
	@Override
	public Products delete(String productsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Products with id: {}", productsId);
        Products deleted = this.wmGenericDao.findById(productsId);
        if (deleted == null) {
            LOGGER.debug("No Products found with id: {}", productsId);
            throw new EntityNotFoundException(String.valueOf(productsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Page<Products> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Products");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Products> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Products");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service classicmodels for table Products to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Orderdetails> findAssociatedOrderdetailsesForProductCode(String productCode, Pageable pageable) {
        LOGGER.debug("Fetching all associated orderdetailsesForProductCode");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("productsByProductCode.productCode = '" + productCode + "'");

        return orderdetailsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Orderdetails> findAssociatedOrderdetailsesForProductCodeRelation(String productCode, Pageable pageable) {
        LOGGER.debug("Fetching all associated orderdetailsesForProductCodeRelation");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("productsByProductCodeRelation.productCode = '" + productCode + "'");

        return orderdetailsService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service OrderdetailsService instance
	 */
	protected void setOrderdetailsService(OrderdetailsService service) {
        this.orderdetailsService = service;
    }

}

